baseURL = "/"
languageCode = ""
paginate = 6
summaryLength = "10"
theme = "parsa"
title = "vonHund"
[[menu.main]]
URL = "performance"
name = "Performance"
weight = "1"
[[menu.main]]
URL = "audio"
name = "Audio"
weight = "3"
[[menu.main]]
URL = "video"
name = "Video"
weight = "2"
[[menu.main]]
URL = "about"
name = "About"
weight = "4"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = "5"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "Raphael Di Canio "
author_image = ""
bio = "blabla"
contact_form_action = "#"
copyright = "Raphael Di Canio &copy; 2020 "
description = "This is meta description"
email = "exmaple@ymail.com"
google_analitycs_id = "Your ID"
home = "works"
layout = "1"
logo = "/images/logokto_klein2.png"
mobile = ""
preloader = true
search = false
social = []
[params.instafeed]
access_token = ""
enable = false
user_id = "3463575825"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
